-- MySQL Script generated by MySQL Workbench
-- Tue Mar 23 10:43:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dtb-sistema-vendas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dtb-sistema-vendas` ;

-- -----------------------------------------------------
-- Schema dtb-sistema-vendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dtb-sistema-vendas` DEFAULT CHARACTER SET utf8 ;
USE `dtb-sistema-vendas` ;

-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`regiao` (
  `id_regiao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_regiao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`estado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `codigo_uf` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `regiao_id_regiao` INT NOT NULL,
  PRIMARY KEY (`id_estado`),
  INDEX `fk_estado_regiao_idx` (`regiao_id_regiao` ASC) VISIBLE,
  CONSTRAINT `fk_estado_regiao`
    FOREIGN KEY (`regiao_id_regiao`)
    REFERENCES `dtb-sistema-vendas`.`regiao` (`id_regiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`cidade` (
  `id_cidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `estado_id_estado` INT NOT NULL,
  PRIMARY KEY (`id_cidade`),
  INDEX `fk_cidade_estado1_idx` (`estado_id_estado` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_id_estado`)
    REFERENCES `dtb-sistema-vendas`.`estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(50) NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `cidade_id_cidade` INT NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_endereco_cidade1_idx` (`cidade_id_cidade` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`cidade_id_cidade`)
    REFERENCES `dtb-sistema-vendas`.`cidade` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`contato` (
  `id_contato` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_contato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`pessoa_juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`pessoa_juridica` (
  `id_pessoa_juridica` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(200) NOT NULL,
  `inscricao_estadual` VARCHAR(50) NOT NULL,
  `cnpj` VARCHAR(50) NOT NULL,
  `data_fundacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pessoa_juridica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`pessoa_fisica` (
  `id_pessoa_fisica` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `data_nascimento` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_pessoa_fisica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `tipo_pessoa` VARCHAR(1) NOT NULL,
  `endereco_id_endereco` INT NOT NULL,
  `contato_id_contato` INT NOT NULL,
  `pessoa_juridica_id_pessoa_juridica` INT NULL,
  `pessoa_fisica_id_pessoa_fisica` INT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_endereco1_idx` (`endereco_id_endereco` ASC) VISIBLE,
  INDEX `fk_cliente_contato1_idx` (`contato_id_contato` ASC) VISIBLE,
  INDEX `fk_cliente_pessoa_juridica1_idx` (`pessoa_juridica_id_pessoa_juridica` ASC) VISIBLE,
  INDEX `fk_cliente_pessoa_fisica1_idx` (`pessoa_fisica_id_pessoa_fisica` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_endereco1`
    FOREIGN KEY (`endereco_id_endereco`)
    REFERENCES `dtb-sistema-vendas`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_contato1`
    FOREIGN KEY (`contato_id_contato`)
    REFERENCES `dtb-sistema-vendas`.`contato` (`id_contato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_pessoa_juridica1`
    FOREIGN KEY (`pessoa_juridica_id_pessoa_juridica`)
    REFERENCES `dtb-sistema-vendas`.`pessoa_juridica` (`id_pessoa_juridica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_pessoa_fisica1`
    FOREIGN KEY (`pessoa_fisica_id_pessoa_fisica`)
    REFERENCES `dtb-sistema-vendas`.`pessoa_fisica` (`id_pessoa_fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`fornecedor` (
  `id_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `contato` VARCHAR(200) NOT NULL,
  `endereco_id_endereco` INT NOT NULL,
  `contato_id_contato` INT NOT NULL,
  `pessoa_juridica_id_pessoa_juridica` INT NOT NULL,
  PRIMARY KEY (`id_fornecedor`),
  INDEX `fk_fornecedor_endereco1_idx` (`endereco_id_endereco` ASC) VISIBLE,
  INDEX `fk_fornecedor_contato1_idx` (`contato_id_contato` ASC) VISIBLE,
  INDEX `fk_fornecedor_pessoa_juridica1_idx` (`pessoa_juridica_id_pessoa_juridica` ASC) VISIBLE,
  CONSTRAINT `fk_fornecedor_endereco1`
    FOREIGN KEY (`endereco_id_endereco`)
    REFERENCES `dtb-sistema-vendas`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_contato1`
    FOREIGN KEY (`contato_id_contato`)
    REFERENCES `dtb-sistema-vendas`.`contato` (`id_contato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_pessoa_juridica1`
    FOREIGN KEY (`pessoa_juridica_id_pessoa_juridica`)
    REFERENCES `dtb-sistema-vendas`.`pessoa_juridica` (`id_pessoa_juridica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `contato_id_contato` INT NOT NULL,
  `endereco_id_endereco` INT NOT NULL,
  `pessoa_fisica_id_pessoa_fisica` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `fk_funcionario_contato1_idx` (`contato_id_contato` ASC) VISIBLE,
  INDEX `fk_funcionario_endereco1_idx` (`endereco_id_endereco` ASC) VISIBLE,
  INDEX `fk_funcionario_pessoa_fisica1_idx` (`pessoa_fisica_id_pessoa_fisica` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_contato1`
    FOREIGN KEY (`contato_id_contato`)
    REFERENCES `dtb-sistema-vendas`.`contato` (`id_contato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_endereco1`
    FOREIGN KEY (`endereco_id_endereco`)
    REFERENCES `dtb-sistema-vendas`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_pessoa_fisica1`
    FOREIGN KEY (`pessoa_fisica_id_pessoa_fisica`)
    REFERENCES `dtb-sistema-vendas`.`pessoa_fisica` (`id_pessoa_fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  `valor_venda` DOUBLE NOT NULL,
  `valor_custo` DOUBLE NOT NULL,
  `fornecedor_id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_produto_fornecedor1_idx` (`fornecedor_id_fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_produto_fornecedor1`
    FOREIGN KEY (`fornecedor_id_fornecedor`)
    REFERENCES `dtb-sistema-vendas`.`fornecedor` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`estoque` (
  `id_estoque` INT NOT NULL AUTO_INCREMENT,
  `quantidade_atual` INT NOT NULL,
  `quantidade_minima` INT NOT NULL,
  `produto_id_produto` INT NOT NULL,
  PRIMARY KEY (`id_estoque`, `produto_id_produto`),
  INDEX `fk_estoque_produto1_idx` (`produto_id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `dtb-sistema-vendas`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(10) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `forma_pagamento` VARCHAR(50) NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_venda_funcionario1_idx` (`funcionario_id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `dtb-sistema-vendas`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `dtb-sistema-vendas`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`item_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`item_venda` (
  `id_item_venda` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `produto_id_produto` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `desconto` DOUBLE NULL,
  `venda_id_venda` INT NOT NULL,
  PRIMARY KEY (`id_item_venda`, `venda_id_venda`),
  INDEX `fk_item_venda_produto1_idx` (`produto_id_produto` ASC) VISIBLE,
  INDEX `fk_item_venda_venda1_idx` (`venda_id_venda` ASC) VISIBLE,
  CONSTRAINT `fk_item_venda_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `dtb-sistema-vendas`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_venda_venda1`
    FOREIGN KEY (`venda_id_venda`)
    REFERENCES `dtb-sistema-vendas`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`contas_receber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`contas_receber` (
  `id_contas_receber` INT NOT NULL AUTO_INCREMENT,
  `data_vencimento` VARCHAR(10) NOT NULL,
  `data_pagamento` VARCHAR(10) NULL,
  `pagamento` VARCHAR(45) NOT NULL,
  `vencida` VARCHAR(45) NOT NULL,
  `venda_id_venda` INT NOT NULL,
  PRIMARY KEY (`id_contas_receber`),
  INDEX `fk_contas_receber_venda1_idx` (`venda_id_venda` ASC) VISIBLE,
  CONSTRAINT `fk_contas_receber_venda1`
    FOREIGN KEY (`venda_id_venda`)
    REFERENCES `dtb-sistema-vendas`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`compra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(10) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `forma_pagamento` VARCHAR(45) NOT NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  `fornecedor_id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_compra_funcionario1_idx` (`funcionario_id_funcionario` ASC) VISIBLE,
  INDEX `fk_compra_fornecedor1_idx` (`fornecedor_id_fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_compra_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `dtb-sistema-vendas`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_fornecedor1`
    FOREIGN KEY (`fornecedor_id_fornecedor`)
    REFERENCES `dtb-sistema-vendas`.`fornecedor` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`item_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`item_compra` (
  `id_item_compra` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `produto_id_produto` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `compra_id_compra` INT NOT NULL,
  PRIMARY KEY (`id_item_compra`, `compra_id_compra`),
  INDEX `fk_item_compra_produto1_idx` (`produto_id_produto` ASC) VISIBLE,
  INDEX `fk_item_compra_compra1_idx` (`compra_id_compra` ASC) VISIBLE,
  CONSTRAINT `fk_item_compra_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `dtb-sistema-vendas`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_compra_compra1`
    FOREIGN KEY (`compra_id_compra`)
    REFERENCES `dtb-sistema-vendas`.`compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`conta_pagar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`conta_pagar` (
  `id_conta_pagar` INT NOT NULL AUTO_INCREMENT,
  `data_vencimento` VARCHAR(10) NOT NULL,
  `data_pagamento` VARCHAR(10) NULL,
  `pagamento` VARCHAR(45) NOT NULL,
  `vencida` VARCHAR(45) NOT NULL,
  `compra_id_compra` INT NOT NULL,
  PRIMARY KEY (`id_conta_pagar`),
  INDEX `fk_conta_pagar_compra1_idx` (`compra_id_compra` ASC) VISIBLE,
  CONSTRAINT `fk_conta_pagar_compra1`
    FOREIGN KEY (`compra_id_compra`)
    REFERENCES `dtb-sistema-vendas`.`compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtb-sistema-vendas`.`log_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dtb-sistema-vendas`.`log_usuario` (
  `funcionario_id_funcionario` INT NOT NULL,
  `timestamp` VARCHAR(45) NOT NULL,
  `operacao` VARCHAR(50) NOT NULL,
  `tabela` VARCHAR(45) NULL,
  INDEX `fk_log_usuario_funcionario1_idx` (`funcionario_id_funcionario` ASC) VISIBLE,
  PRIMARY KEY (`timestamp`),
  CONSTRAINT `fk_log_usuario_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `dtb-sistema-vendas`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
